on:
  workflow_call:
    secrets:
      jira_base_url:
        required: true
      jira_user_email:
        required: true
      jira_api_token:
        required: true

name: Transition Ticket on PR Closure
jobs:
  close-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.jira_base_url }}
          JIRA_USER_EMAIL: ${{ secrets.jira_user_email }}
          JIRA_API_TOKEN: ${{ secrets.jira_api_token }}
      - id: jira-ticket-id
        run:  echo "::set-output name=jira-ticket-id::`echo "${{ github.event.pull_request.title }}" | sed 's/ .*//'`"
      - name: Close Jira Ticket assocaited with PR
        uses: atlassian/gajira-transition@v2.0.2
        id: jira-ticket
        with:
          issue: ${{ steps.jira-ticket-id.outputs.jira-ticket-id }}
          transition: "Done"
